[general]

host = "::"
port = 9333
root = "/app/ui"
log-level = "info"

page-fallback = "/app/ui/index.html"
cache-control-headers = true
compression = true
security-headers = true
directory-listing = false
redirect-trailing-slash = true
compression-static = true
ignore-hidden-files = true
